repository:
  name: test-repository-settings-app
  default_branch: main
  delete_branch_on_merge: true
  topics: cdktf, js
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: null
      required_linear_history: null
      restrictions: null
environments:
  - name: dev
    wait_timer: 10
    reviewers:
      - id: 1110255
        type: User
    deployment_branch_policy:
      protected_branches: true
