repository:
  name: test-repository-settings-app
  default_branch: main
  has_issues: false
  has_wiki: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: false
  delete_branch_on_merge: true
  topics: cdktf, infra, platform
collaborators:
  - username: rlmartin
    permission: admin
