repository:
  name: test-repository-settings-app
  default_branch: main
  delete_branch_on_merge: true
  topics: cdktf, js
environments:
  - name: dev
    wait_timer: 10
    reviewers:
      - id: 1110255
        type: User
    deployment_branch_policy:
      protected_branches: true
